### PR TITLE
Fix for TypeScript, adding some tests and fixing typos

### PR DESCRIPTION
**Pull request by visvirial**
In this PR, I fixed some transformation errors on TypeScript, added WebWorker tests and fixed some other minor issues.

- The variable `desideredWrappedSrc` seems to be a typo and was renamed to `desiredWrappedSrc`.
- The execution fails if there are no `import` statements in the `*.worker.(js|ts)` files. Fixed.
- Added `EchoWorker` tests (both for JavaScript and TypeScript) which test the execution of WebWorker transformation.

Known issues (should be fixed in the future):
- The files imported in the `*.worker.ts` should be a JavaScript file and cannot be a TypeScript file.
- If there is a comment or something which contains the string `import`, `./utils/stripper.js` considers it as a module imports, and outputs a wrong JS string.
  - Try adding a comment `// This will import mylibrary.` to `./__test__/echoworker.worker.js` somewhere. This will throw a `SyntaxError`.
  - The `importRe` regular expression in `./utils/stripper.js` should be sophisticated, and / or some syntax interpretation should be applied.

(Note: if you encountered an error by executing Jest, please clear your cache using `jest --clearCache` and / or just using `jest --no-cache`)

### CODE REVIEW

**Comment by astagi** [comment]
@visvirial this PR looks awesome! thank you so much! Yeah I opened this repo as a little experimental module, I'm very happy to see contributions and interest on it!

**Comment by visvirial** [comment]
When will it be merged?

**Comment by astagi** [comment]
@visvirial I'll check it during the weekend! I'll merge it on Monday and then draft a new release on NPM! Sorry but I'm very busy at the moment! Thank you for the awesome work, let you know asap

**Comment by astagi** [comment]
@visvirial in the meantime please add yourself to [CONTRIBUTORS](https://github.com/astagi/workerloader-jest-transformer/blob/master/CONTRIBUTORS.md)

**Comment by visvirial** [comment]
That's okay. I'm not in a hurry but I just wanted to make sure that my PR is surely in a review.
Have a nice weekend!

**Review by astagi — APPROVED** [review]

**Comment by astagi** [comment]
Again, awesome work @visvirial , thank you so much! Version 0.0.4 is now available on [npm](https://www.npmjs.com/package/workerloader-jest-transformer) 

> * The files imported in the `*.worker.ts` should be a JavaScript file and cannot be a TypeScript file.

Mmh that's interesting, it's been a long time since I looked at this code last time, also I never tried importing typescript files inside the worker, what's wrong with them?

> * If there is a comment or something which contains the string `import`, `./utils/stripper.js` considers it as a module imports, and outputs a wrong JS string.
>   
>   * Try adding a comment `// This will import mylibrary.` to `./__test__/echoworker.worker.js` somewhere. This will throw a `SyntaxError`.
>   * The `importRe` regular expression in `./utils/stripper.js` should be sophisticated, and / or some syntax interpretation should be applied.
> 

You're right, import is a reserved word but it can be used in a comment or in a string, I think that a more sophisticated regular expression may intercept it, without diving into syntax interpretation (I suppose you're talking about using AST, right?)

**Comment by visvirial** [comment]
Yes, I mean some AST should be employed to be more strictly.

However, since that `import` statement will appear at the beginning of lines, how about appending the letter '^' to the beginning of `importsRe` in `utils/stripper.js`?
(Note: also dynamic imports like `const foo = await import('foo')` shouldn't be matched.)

**Comment by visvirial** [comment]
Uh, this won't work for `import` statements in a multiple line comments:
```ts
/**
import bar from 'bar';
*/
```
This will match the regex...

-----

The most reliable and straight forward way, I think, is to force `*.worker.ts` to include `/* __SEPARATOR__ */` as in https://github.com/visvirial/jest-webworker

**Pull request merged**
